language: node_js
node_js:
  - "0.10"

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/$GITTER_WEBHOOK_TOKEN
#    on_success: always
#    on_failure: always
#    on_start: always
